### PR TITLE
issues#310: Fix orderbook summary

### PR DESCRIPTION
**Pull request by akirattii**
issues#310
Fix orderbook summary order.

### CODE REVIEW

**Review by nullstyle — CHANGES_REQUESTED** [review]
@akirattii Is it possible for you to add a regression test for this fix?

Our test suite isn't the best for horizon, but I feel like this issue is subtle enough that we should certainly cover it in our integration test suite.

I would add a new test scenario into the `test/scenarios` folder (I would use `order_books.rb` as the template, modifying it as necessary), then add a new test function called `TestOrderBookActions_Issue310` into the `actions_order_book_test.go` file.

I'm happy to advise and fill in code if/where you hit snags.

**Comment by ghost** [comment]
Sorry, my skill is not enough for testing that. Instead of that, I put the sql I queried and its results below. If it's okay with you, please check this and come up with any appropriate testing code.

### SQL(BEFORE):

```
SELECT
    *,
    (pricen :: double precision / priced :: double precision) as pricef

FROM
((
    -- This query returns the "asks" portion of the summary, and it is very straightforward
    SELECT
        'ask' as type,
        co.pricen,
        co.priced,
        SUM(co.amount) as amount

    FROM  offers co

    WHERE 1=1
    AND   co.sellingassettype = 1
    AND   co.sellingassetcode = 'JPY'
    AND   co.sellingissuer = 'GA57TRMYNOYNY6O6OGLKSMYWRN7RQT5MMV34FWR6XV5FXPXLCCNZSMLN'
    AND   co.buyingassettype = 1
    AND   co.buyingassetcode = 'AAA'
    AND   co.buyingissuer = 'GA57TRMYNOYNY6O6OGLKSMYWRN7RQT5MMV34FWR6XV5FXPXLCCNZSMLN'

    GROUP BY
        co.pricen,
        co.priced,
        co.price

    LIMIT 20

) UNION (
    -- This query returns the "bids" portion, inverting the where clauses
    -- and the pricen/priced.  This inversion is necessary to produce the "bid"
    -- view of a given offer (which are stored in the db as an offer to sell)
    SELECT
        'bid'  as type,
        co.priced as pricen,
        co.pricen as priced,
        SUM(co.amount) as amount

    FROM offers co

    WHERE 1=1
    AND   co.sellingassettype = 1
    AND   co.sellingassetcode = 'AAA'
    AND   co.sellingissuer = 'GA57TRMYNOYNY6O6OGLKSMYWRN7RQT5MMV34FWR6XV5FXPXLCCNZSMLN'
    AND   co.buyingassettype = 1
    AND   co.buyingassetcode = 'JPY'
    AND   co.buyingissuer = 'GA57TRMYNOYNY6O6OGLKSMYWRN7RQT5MMV34FWR6XV5FXPXLCCNZSMLN'

    GROUP BY
        co.pricen,
        co.priced,
        co.price

    LIMIT 20
)) summary

ORDER BY type, pricef
```

### RESULT(BEFORE):

```
type |  pricen  |  priced  |   amount    |      pricef       
------+----------+----------+-------------+-------------------
 ask  |       50 |       51 | 99745800000 | 0.980392156862745
 ask  |     1000 |     1001 |    10010000 | 0.999000999000999
 ask  |        1 |        1 |   990000000 |                 1
 ask  |      100 |       99 |   990000000 |  1.01010101010101
 ask  |       50 |       49 |   980000000 |  1.02040816326531
 ask  |      100 |       97 |   970000000 |  1.03092783505155
 ask  |       25 |       24 |   960000000 |  1.04166666666667
 ask  |       20 |       19 |   950000000 |  1.05263157894737
 ask  |       50 |       47 |   940000000 |  1.06382978723404
 ask  |      100 |       93 |   930000000 |   1.0752688172043
 ask  |       25 |       23 |   920000000 |  1.08695652173913
 ask  |      100 |       89 |   890000000 |  1.12359550561798
 ask  |       25 |       22 |   880000000 |  1.13636363636364
 ask  |      100 |       87 |   870000000 |  1.14942528735632
 ask  |       50 |       43 |   860000000 |  1.16279069767442
 ask  |       20 |       17 |   850000000 |  1.17647058823529
 ask  |       25 |       21 |   840000000 |  1.19047619047619
 ask  |      100 |       83 |   830000000 |  1.20481927710843
 ask  |       50 |       41 |   820000000 |  1.21951219512195
 ask  |      100 |       81 |   810000000 |  1.23456790123457
 bid  |        5 |        6 |  1000000000 | 0.833333333333333
 bid  |      100 |      119 |  1000000000 | 0.840336134453782
 bid  |       50 |       59 |  1000000000 | 0.847457627118644
 bid  |      100 |      117 |  1000000000 | 0.854700854700855
 bid  |       25 |       29 |  1000000000 | 0.862068965517241
 bid  |       20 |       23 |  1000000000 | 0.869565217391304
 bid  |       50 |       57 |  1000000000 |  0.87719298245614
 bid  | 10000000 | 11299999 |  1000000000 | 0.884955830527065
 bid  |       25 |       28 |  1000000000 | 0.892857142857143
 bid  |      100 |      111 |  1000000000 | 0.900900900900901
 bid  |       10 |       11 |  1000000000 | 0.909090909090909
 bid  |      100 |      109 |  1000000000 | 0.917431192660551
 bid  |       25 |       27 |  1000000000 | 0.925925925925926
 bid  |      100 |      107 |   400000000 | 0.934579439252336
(34 rows)
```

### SQL(AFTER):

```
SELECT
    *,
    (pricen :: double precision / priced :: double precision) as pricef

FROM
((
    -- This query returns the "asks" portion of the summary, and it is very straightforward
    SELECT
        'ask' as type,
        co.pricen,
        co.priced,
        SUM(co.amount) as amount

    FROM  offers co

    WHERE 1=1
    AND   co.sellingassettype = 1
    AND   co.sellingassetcode = 'JPY'
    AND   co.sellingissuer = 'GA57TRMYNOYNY6O6OGLKSMYWRN7RQT5MMV34FWR6XV5FXPXLCCNZSMLN'
    AND   co.buyingassettype = 1
    AND   co.buyingassetcode = 'AAA'
    AND   co.buyingissuer = 'GA57TRMYNOYNY6O6OGLKSMYWRN7RQT5MMV34FWR6XV5FXPXLCCNZSMLN'

    GROUP BY
        co.pricen,
        co.priced,
        co.price

    -- Added:
    ORDER BY co.price

    LIMIT 20

) UNION (
    -- This query returns the "bids" portion, inverting the where clauses
    -- and the pricen/priced.  This inversion is necessary to produce the "bid"
    -- view of a given offer (which are stored in the db as an offer to sell)
    SELECT
        'bid'  as type,
        co.priced as pricen,
        co.pricen as priced,
        SUM(co.amount) as amount

    FROM offers co

    WHERE 1=1
    AND   co.sellingassettype = 1
    AND   co.sellingassetcode = 'AAA'
    AND   co.sellingissuer = 'GA57TRMYNOYNY6O6OGLKSMYWRN7RQT5MMV34FWR6XV5FXPXLCCNZSMLN'
    AND   co.buyingassettype = 1
    AND   co.buyingassetcode = 'JPY'
    AND   co.buyingissuer = 'GA57TRMYNOYNY6O6OGLKSMYWRN7RQT5MMV34FWR6XV5FXPXLCCNZSMLN'

    GROUP BY
        co.pricen,
        co.priced,
        co.price

    -- Added:
    ORDER BY co.price

    LIMIT 20
)) summary

ORDER BY type, pricef
```

I added `ORDER BY co.price` in the 2 places, which are in the 2nd & 3rd `SELECT`.

### RESULT(AFTER):

```
 type |  pricen  |  priced  |   amount    |      pricef       
------+----------+----------+-------------+-------------------
 ask  |       50 |       51 | 99745800000 | 0.980392156862745
 ask  |      100 |      101 | 99101200000 |  0.99009900990099 <= Appeared!
 ask  |     1000 |     1001 |    10010000 | 0.999000999000999
 ask  |        1 |        1 |   990000000 |                 1
 ask  |      100 |       99 |   990000000 |  1.01010101010101
 ask  |       50 |       49 |   980000000 |  1.02040816326531
 ask  |      100 |       97 |   970000000 |  1.03092783505155
 ask  |       25 |       24 |   960000000 |  1.04166666666667
 ask  |       20 |       19 |   950000000 |  1.05263157894737
 ask  |       50 |       47 |   940000000 |  1.06382978723404
 ask  |      100 |       93 |   930000000 |   1.0752688172043
 ask  |       25 |       23 |   920000000 |  1.08695652173913
 ask  |      100 |       91 |   910000000 |   1.0989010989011 <= Appeared!
 ask  |       10 |        9 |   900000000 |  1.11111111111111 <= Appeared!
 ask  |      100 |       89 |   890000000 |  1.12359550561798
 ask  |       25 |       22 |   880000000 |  1.13636363636364
 ask  |      100 |       87 |   870000000 |  1.14942528735632
 ask  |       50 |       43 |   860000000 |  1.16279069767442
 ask  |       20 |       17 |   850000000 |  1.17647058823529
 ask  |       25 |       21 |   840000000 |  1.19047619047619
 bid  |        5 |        6 |  1000000000 | 0.833333333333333
 bid  |      100 |      119 |  1000000000 | 0.840336134453782
 bid  |       50 |       59 |  1000000000 | 0.847457627118644
 bid  |      100 |      117 |  1000000000 | 0.854700854700855
 bid  |       25 |       29 |  1000000000 | 0.862068965517241
 bid  |       20 |       23 |  1000000000 | 0.869565217391304
 bid  |       50 |       57 |  1000000000 |  0.87719298245614
 bid  | 10000000 | 11299999 |  1000000000 | 0.884955830527065
 bid  |       25 |       28 |  1000000000 | 0.892857142857143
 bid  |      100 |      111 |  1000000000 | 0.900900900900901
 bid  |       10 |       11 |  1000000000 | 0.909090909090909
 bid  |      100 |      109 |  1000000000 | 0.917431192660551
 bid  |       25 |       27 |  1000000000 | 0.925925925925926
 bid  |      100 |      107 |   400000000 | 0.934579439252336
(34 rows)
```

**Comment by nullstyle** [comment]
@akirattii Thanks for the update.  I appreciate the honesty regarding the test:  totally makes sense.  We at stellar need to do a better job about building our test suite to be comprehensible to outside developers, but that's neither here nor there.

I'll carve out a couple hours today and tomorrow to write a test of my own for this issue.  If I can't get it done along with all the other work on my plate, we'll go ahead and merge this tomorrow afternoon.  In the meantime I'll try to make sure we have some assurances that future updates don't cause this bug to resurface.

**Comment by ghost** [comment]
@nullstyle Thank you. 
Well my PR was a bit insufficient. So I want you to use this latest patch:

```
--- order_book_summary.go    2016-10-12 06:53:03.310714079 +0900
+++ order_book_summary.go.new    2016-10-12 06:51:43.395684697 +0900
@@ -129,6 +129,9 @@
         co.pricen,
         co.priced,
         co.price
+
+    ORDER BY co.price
+
     LIMIT $1

 ) UNION (
@@ -155,6 +158,9 @@
         co.pricen,
         co.priced,
         co.price
+
+    ORDER BY co.price
+
     LIMIT $1
 )) summary
```

**Comment by nullstyle** [comment]
@akirattii could you checkout https://github.com/stellar/horizon/pull/315 and see if it solves the issue for you.

i'm going to go ahead and close this PR, since mine has tests.  Please note that your change had an additional bug in it:  Bids needed to be sorted descending, not ascending, to get the correct behavior.  Your scenario only succeeds because there are fewer than 20 bids in that particular order book.

Thanks for the report!

**Pull request closed without merging**
