### PR TITLE
Some refactoring of db

### PR DESCRIPTION
**Pull request by gterzian**
just trying some stuff, WIP

### CODE REVIEW

**Comment by gterzian** [comment]
@nullstyle This might be a bit 'useless', and it could still represent a step towards more re-use of implementations across `records` structs within the `db` package. 

For me it was mainly a useful exercise, and the first lines of Go I ever wrote. Please let me know what you think and merge at your own risk! :smile:

**Comment by nullstyle** [comment]
Hi @gterzian, 

First of all, thanks!

I think you're on to something here, but I wanted to just offer a bit of advice.  I'm concerned that `RecordBase` is a bit too generic a term.  I don't want the non-horizon-specific types in the db package to make assumptions about the database structure, and IMO `RecordBase` implies non-horizon-specific. 

That type is encoding "Has an id attribute, which is used for the paging token as-is"  and given the design of horizon that is mostly going to apply to members of the history database.  As such, I personally would prefer we name that `HistoryRecord` to begin with, and upgrade to a more common name (perhaps `IDBasedRecord`?)  if necessary.   Does that make sense?

**Comment by gterzian** [comment]
@nullstyle yep that makes a lot of sense, so I renamed the struct to `HistoryRecord`. By the way which parts of the db module are non-horizon specific? Sorry I was actually not entirely aware of the distinction :laughing:

**Comment by nullstyle** [comment]
@gterzian,

No worries about not knowing the distinction...  it's worth noting that go-horizon is the first go codebase I've built beyond play apps and prototypes, so I'm sure I will make many facepalm-worthy mistakes that will trip other developers up.

As far as the non-specific db pieces... it's basically `main.go` `query_sql.go` and the `streaming*.go` files.

I'm presently working on changing up the streaming system, and it will probably be removed and replaced by a system that is driven from the http request, rather than the db query.

**Comment by gterzian** [comment]
@nullstyle Sounds good, and looks good so far as well for a first "serious" project :smile: 

I rebased and fixed some small build errors, please take a look.

**Comment by nullstyle** [comment]
Thanks @gterzian ! :+1:

**Pull request merged**
