### PR TITLE
set Access-Control-Allow-Origin to *

### PR DESCRIPTION
**Pull request by FredericHeem**

### CODE REVIEW

**Comment by nullstyle** [comment]
@FredericHeem this is already handled by the cors middleware we use:  https://github.com/stellar/go-horizon/blob/master/src/github.com/stellar/go-horizon/init_web.go#L59

**Comment by FredericHeem** [comment]
That's weird because I had cors issues without this patch. Are you sure the cors middleware works ?

**Comment by nullstyle** [comment]
yep:

```
$ http :8000/ Origin:foo.com
HTTP/1.1 200 OK
Access-Control-Allow-Origin: foo.com
....
```

It's worth noting that you won't see the headers if you don't send an `Origin` header, but any modern browser should be sending that along just fine.

**Comment by nullstyle** [comment]
I certainly need to add a test for it, though (going to do that now)

**Comment by FredericHeem** [comment]
The frontend is angular based, is there anything special to set ?

**Comment by nullstyle** [comment]
I'm betting one of the other headers being sent up is causing the cors pre-flight request to fail.    Do you have a repro you can share?  I'll go ahead and add some of the allowed headers into the list in the meantime.

**Comment by FredericHeem** [comment]
The _Origin_ http header is in the form of _http://myapp.com_, don't know if the http prefix is messing around.

**Pull request closed without merging**
