### PR TITLE
go-horizon to horizon

### PR DESCRIPTION
**Pull request by bartekn**
Changed `go-horizon` to `horizon` and renamed project dir.

Should fix tests in #91 (after rebasing).

### CODE REVIEW

**Comment by nullstyle** [comment]
These changes should not have any bearing on whether the tests run successfully or not.  Let's actually dig in to why the tests aren't running.

**Comment by nullstyle** [comment]
@bartekn FYI: I've rebase this PR onto the top of master

**Comment by nullstyle** [comment]
:+1:

**Comment by bartekn** [comment]
:+1:

**Pull request merged**
